name: dvL-den
favicon: null
layout_spectrum: 0.24601
typography_spectrum: 0.18388
title: dvL-den
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9dfed0'
    - '#5d5d5d'
    - '#99baaa'
    - '#020202'
    - '#ffffff'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
